#!/bin/bash
for f in $(ls *.swift); do
    if [ $f != "utils.swift" ]; then
        binfile=${f%.*}
        cat utils.swift $f | swiftc - -O -o ../bin/$binfile
        echo "Compiled $f to ../bin/$binfile"
    fi
done
